using Microsoft.EntityFrameworkCore;
using SchemaTrail.Abstractions;
using SchemaTrail.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace SchemaTrail;

/// <summary>
/// Implements migration execution operations, including infrastructure preparation,
/// loading and validating applied migrations, and applying individual migrations.
/// </summary>
public sealed class MigrationExecutionService : IMigrationExecutionService
{
    /// <inheritdoc />
    public async Task EnsureInfrastructureTablesExistAsync(
        MigrationsDbContext context,
        CancellationToken token )
    {
        ArgumentNullException.ThrowIfNull( context );

        var migrationTableName = MigrationsDbContext.STORAGE_MIGRATION_TABLENAME;

        var sql =
            $"""
            create table if not exists {migrationTableName}
            (
                version integer not null primary key,
                script_name text not null unique,
                description text not null,
                checksum text not null,
                applied_at timestamp with time zone not null default (now() at time zone 'utc')
            );

            create table if not exists {migrationTableName}_runs
            (
                id bigint generated by default as identity primary key,
                version integer not null,
                script_name text not null,
                description text not null,
                checksum text not null,
                status text not null,
                started_at timestamp with time zone not null,
                completed_at timestamp with time zone null,
                duration_ms bigint null,
                error_text text null,
                constraint ck_{migrationTableName}_runs_status
                    check (status in ('running', 'success', 'failed'))
            );

            create index if not exists ix_{migrationTableName}_runs_version_started_at
                on {migrationTableName}_runs (version, started_at desc);

            create index if not exists ix_{migrationTableName}_script_name
                on {migrationTableName} (script_name);
            """;

        await context.Database.ExecuteSqlRawAsync( sql, token );
    }

    /// <inheritdoc />
    public async Task<Dictionary<int, AppliedMigration>> LoadAppliedMigrationsAsync(
        MigrationsDbContext context,
        CancellationToken token )
    {
        ArgumentNullException.ThrowIfNull( context );

        return await context.AppliedMigrations
            .AsNoTracking()
            .OrderBy( x => x.Version )
            .ToDictionaryAsync(
                x => x.Version,
                x => new AppliedMigration(
                    x.Version,
                    x.ScriptName,
                    x.Description,
                    x.Checksum,
                    x.AppliedAt ),
                token );
    }

    /// <inheritdoc />
    public void ValidateAlreadyAppliedMigrations(
        IReadOnlyList<SqlScriptMigration> scripts,
        IReadOnlyDictionary<int, AppliedMigration> appliedMigrations )
    {
        ArgumentNullException.ThrowIfNull( scripts );
        ArgumentNullException.ThrowIfNull( appliedMigrations );

        var scriptMap = scripts.ToDictionary( x => x.Version );

        foreach (var (version, applied) in appliedMigrations) {
            if (!scriptMap.TryGetValue( version, out var currentScript )) {
                throw new InvalidOperationException(
                    $"Database contains migration V{version:D3} ({applied.ScriptName}), "
                    + "but current application build does not contain this migration. "
                    + "Most likely an older application version is running against a newer database." );
            }

            if (!string.Equals( applied.ScriptName, currentScript.ScriptName, StringComparison.Ordinal )) {
                throw new InvalidOperationException(
                    $"Migration V{version:D3} was already applied as '{applied.ScriptName}', "
                    + $"but current build contains '{currentScript.ScriptName}'. "
                    + "Renaming applied migration files is not allowed." );
            }

            if (!string.Equals( applied.Description, currentScript.Description, StringComparison.Ordinal )) {
                throw new InvalidOperationException(
                    $"Migration V{version:D3} was already applied with description '{applied.Description}', "
                    + $"but current build contains description '{currentScript.Description}'." );
            }

            if (!string.Equals( applied.Checksum, currentScript.Checksum, StringComparison.Ordinal )) {
                throw new InvalidOperationException(
                    $"Checksum mismatch detected for migration V{version:D3} ({currentScript.ScriptName}). "
                    + "The migration has already been applied, but its SQL content has been changed." );
            }
        }
    }

    /// <inheritdoc />
    public async Task<DateTimeOffset> ApplySingleMigrationAsync(
        MigrationsDbContext context,
        SqlScriptMigration script,
        CancellationToken token )
    {
        ArgumentNullException.ThrowIfNull( context );
        ArgumentNullException.ThrowIfNull( script );

        await using var transaction =
            await context.Database.BeginTransactionAsync( IsolationLevel.ReadCommitted, token );

        try {
            await context.Database.ExecuteSqlRawAsync( script.Sql, token );

            var appliedAt = DateTimeOffset.UtcNow;

            context.AppliedMigrations.Add(
                new MigrationEntity {
                    Version = script.Version,
                    ScriptName = script.ScriptName,
                    Description = script.Description,
                    Checksum = script.Checksum,
                    AppliedAt = appliedAt,
                } );

            await context.SaveChangesAsync( token );
            await transaction.CommitAsync( token );

            context.ChangeTracker.Clear();

            return appliedAt;
        }
        catch {
            await transaction.RollbackAsync( CancellationToken.None );
            context.ChangeTracker.Clear();
            throw;
        }
    }
}